TypeError: Cannot read properties of undefined (reading 'jwtToken')
Solution: in app.js of server
const cookieParser = require('cookie-parser')
app.use(cookieParser())